version: '3.8'

services:
  frontend:
    build:
      context: ./bunz-studio
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./bunz-studio:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./bunz-studio
          target: /src
          ignore:
            - node_modules/

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
    command: sh -c "npm run prebuild && npm run server"
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_DEVICE_NAME=docker-dev
    command: [
      "listen",
      "--api-key", "${STRIPE_SECRET_KEY}",
      "--device-name", "docker-dev",
      "--skip-verify",
      "--forward-to", "http://backend:8080/api/webhooks/stripe"
    ]
    depends_on:
      - backend
    networks:
      - default

volumes:
  redis_data: