version: '3.8'

services:
  frontend:
    build:
      context: ./bunz-studio
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./bunz-studio:/src
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm run prebuild && npm run server"