version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SERVICE_USER_MONGODB}
      MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_PASSWORD_MONGODB}
      MONGO_INITDB_DATABASE: nuxt_anime
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Backend API Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Database connection using Coolify magic variables
      MONGODB_URI: mongodb://${SERVICE_USER_MONGODB}:${SERVICE_PASSWORD_MONGODB}@mongodb:27017/nuxt_anime?authSource=admin
      
      # JWT Secret
      JWT_SECRET: ${SERVICE_PASSWORD_JWT}
      
      # Stripe Configuration
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      
      # Google Cloud Configuration
      GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID}
      GOOGLE_CLOUD_KEYFILE: ${GOOGLE_CLOUD_KEYFILE}
      
      # Twilio Configuration
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      
      # Email Configuration
      NODEMAILER_USER: ${NODEMAILER_USER}
      NODEMAILER_PASS: ${NODEMAILER_PASS}
      
      # Server Configuration
      PORT: 8080
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./server/google-api-credentials.json:/app/google-api-credentials.json:ro

  # Frontend Nuxt Application
  frontend:
    build:
      context: ./bunz-studio
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # API URL using Coolify magic variable for backend service
      API_URL: ${SERVICE_FQDN_BACKEND}
      
      # Stripe Public Key
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      
      # Google OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      
      # Nuxt Configuration
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge