# syntax = docker/dockerfile:1
FROM node:20.12.2-alpine3.18 as base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json package-lock.json .
RUN npm install

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules
COPY --link package.json package-lock.json .

CMD [ "npm", "run", "dev" ]